# Generated by Django 4.2.14 on 2024-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0003_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
